name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Setup JDK
      uses: actions/setup-java@v2.3.1
      with:
        java-version: 11
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./Application/gradlew
    - name: Build with Gradle
      run: ./Application/gradlew build
    - name: Upload APK
      uses: actions/upload-artifact@v2.2.4
      with:
        name: app
        path: Application/app/build/outputs/apk/debug/app-debug.apk
